"""CAVER 3.0 integration for the Tunneler plugin -- locate (or fetch) the GPLv3 CAVER
engine, generate a run config, invoke it, and point at its output. Pure logic: NO tkinter,
NO yasara imports, so it is importable and unit-testable headlessly (unlike the GUI module).

IMPORTANT: this is a helper MODULE imported by the plugin, not a standalone plugin. It must
NOT begin with a plugin menu-header comment block -- YASARA scans every .py in plg/ and tries
to parse any such file as a plugin, then crashes on the non-conforming body (error 366, 'no
colon'). Like the other Tunneler_*.py helpers, it starts with a plain docstring so YASARA's
plugin scanner skips it. Keep the marker phrase out of this file entirely.

CAVER 3.0 (https://caver.cz) is separate GPLv3 software by Loschmidt Laboratories, Masaryk
University. This plugin does not redistribute it; it is fetched from the official site on
first use (source + license included in that download), or the user points at an existing
install. Only the GPLv3 CAVER 3.0 engine is used -- never the non-commercial CAVER Analyst /
CaverDock / Caver Web components.
"""

import os
import shutil
import subprocess
import zipfile

# Official PLoS build: GPLv3, ships full source_code/ tree.
CAVER_DOWNLOAD_URL = 'https://www.caver.cz/fil/download/caver30/plos/caver_3.0.zip'
# Managed install location (user-writable, survives plugin updates). ~ expands via HOME.
DEFAULT_CAVER_ROOT = os.path.expanduser(os.path.join('~', '.tunneler', 'caver_3.0'))
# Remembers a resolved/browsed CAVER home across sessions. Kept OUT of Tunneler_config.ini
# (which Tunneler() rewrites every detection run and would wipe an unknown key).
CAVER_HOME_MEMO = os.path.expanduser(os.path.join('~', '.tunneler', 'caver_home.txt'))

# Minimal run config. The five run-time knobs are placeholders; everything else mirrors
# CAVER's own config_default.txt closely enough to produce the clusters_timeless output
# the importer reads. VMD/trajectory lines are dropped (we visualise in YASARA).
CONFIG_TEMPLATE = """\
# Generated by the YASARA Tunneler plugin -- CAVER 3.0 run config
load_tunnels no
load_cluster_tree no
stop_after never

time_sparsity 1
first_frame 1
last_frame 100000

# Tunnel origin (from the residue/atom picked in YASARA)
starting_point_coordinates {start_x:.3f} {start_y:.3f} {start_z:.3f}

probe_radius {probe_radius}
shell_radius {shell_radius}
shell_depth {shell_depth}

clustering average_link
weighting_coefficient 1
clustering_threshold {clustering_threshold}

exclude_start_zone 2
exclude_end_zone 0
min_middle_zone 5
save_zones no

one_tunnel_in_snapshot cheapest
max_output_clusters 999
save_dynamics_visualization no

generate_summary yes
generate_tunnel_characteristics yes
generate_tunnel_profiles yes
generate_histograms no
generate_bottleneck_heat_map no
generate_profile_heat_map no
compute_tunnel_residues no
compute_bottleneck_residues no

max_distance 3
desired_radius 5
number_of_approximating_balls 12
add_central_sphere yes
max_number_of_tunnels 10000
max_limiting_radius 100
cost_function_exponent 2
automatic_shell_radius no
starting_point_protection_radius 4

frame_clustering yes
frame_weighting_coefficient 1
frame_clustering_threshold 1

average_surface_frame yes
average_surface_global yes

do_approximate_clustering no
generate_unclassified_cluster no

profile_tunnel_sampling_step 0.5
visualization_tunnel_sampling_step 1
visualize_tunnels_per_cluster 5000
visualization_subsampling random

compute_errors no
save_error_profiles no
generate_trajectory no

swap yes
seed 1
{include_line}"""


def find_java():
    """Path to the java launcher, or None if Java isn't on PATH."""
    return shutil.which('java')


def caver_home_valid(path):
    """True if `path` is a usable CAVER home (has caver.jar and a lib/ dir)."""
    return bool(path) and os.path.isfile(os.path.join(path, 'caver.jar')) \
        and os.path.isdir(os.path.join(path, 'lib'))


def _search_caver_home(root):
    """Find a dir containing caver.jar + lib/ anywhere under `root` (handles the zip's
    nested caver_3.0/caver/ layout), or None."""
    if not root or not os.path.isdir(root):
        return None
    for dirpath, dirs, files in os.walk(root):
        if 'caver.jar' in files and 'lib' in dirs:
            return dirpath
    return None


def remembered_caver_home():
    """The CAVER home saved by a previous browse/download, if still valid; else None."""
    try:
        with open(CAVER_HOME_MEMO) as f:
            path = f.read().strip()
    except OSError:
        return None
    return path if caver_home_valid(path) else None


def remember_caver_home(path):
    """Persist `path` as the CAVER home for future sessions (best-effort)."""
    try:
        os.makedirs(os.path.dirname(CAVER_HOME_MEMO), exist_ok=True)
        with open(CAVER_HOME_MEMO, 'w') as f:
            f.write(path)
    except OSError:
        pass


def find_caver_home(hint=None):
    """Return a valid CAVER home dir or None. Checks, in order: the explicit `hint` (which
    may be the caver dir itself, its parent run-root, or a tree to search), the remembered
    path from a previous session, then the managed install under DEFAULT_CAVER_ROOT.
    Returns None if nothing valid is found (caller then offers download / manual pick)."""
    for cand in (hint, os.path.join(hint or '', 'caver')):
        if caver_home_valid(cand):
            return cand
    remembered = remembered_caver_home()
    if remembered:
        return remembered
    for root in (hint, DEFAULT_CAVER_ROOT):
        found = _search_caver_home(root)
        if found:
            return found
    return None


def download_caver(progress_cb=None, url=CAVER_DOWNLOAD_URL, dest_root=DEFAULT_CAVER_ROOT):
    """Download + extract the official CAVER zip into `dest_root`; return the caver home
    dir. `progress_cb(pct)` is called during download if given. Raises on failure."""
    import urllib.request
    os.makedirs(dest_root, exist_ok=True)
    zip_path = os.path.join(dest_root, '_caver_download.zip')

    def _hook(blocks, blocksize, total):
        if progress_cb and total > 0:
            progress_cb(min(100, int(blocks * blocksize * 100 / total)))

    try:
        urllib.request.urlretrieve(url, zip_path, _hook)
        with zipfile.ZipFile(zip_path) as z:
            z.extractall(dest_root)
    finally:
        if os.path.exists(zip_path):
            os.remove(zip_path)
    home = _search_caver_home(dest_root)
    if not home:
        raise RuntimeError('CAVER downloaded but caver.jar was not found after extraction.')
    return home


def make_config(start_xyz, probe_radius=0.9, shell_radius=3, shell_depth=4,
                clustering_threshold=3.5, include_residue_names=None):
    """Return the text of a CAVER config for a single static structure, with the tunnel
    origin fixed at `start_xyz` (a 3-tuple in the structure's coordinate frame)."""
    x, y, z = start_xyz
    include_line = ('include_residue_names ' + include_residue_names) if include_residue_names else ''
    return CONFIG_TEMPLATE.format(
        start_x=x, start_y=y, start_z=z,
        probe_radius=probe_radius, shell_radius=shell_radius,
        shell_depth=shell_depth, clustering_threshold=clustering_threshold,
        include_line=include_line)


def build_command(java, caver_home, input_dir, config_path, out_dir, heap_mb=2000):
    """Assemble the CAVER launch command (matches the package's own static examples:
    java -jar caver.jar -home <caver> -pdb <input dir> -conf <config> -out <out>)."""
    return [java, '-Xmx{}m'.format(heap_mb), '-jar',
            os.path.join(caver_home, 'caver.jar'),
            '-home', caver_home, '-pdb', input_dir, '-conf', config_path, '-out', out_dir]


def start_caver(java, caver_home, input_dir, config_path, out_dir, heap_mb=2000):
    """Launch CAVER as a background subprocess and return the Popen handle. stdout/stderr
    are captured so the caller can poll .poll() and read output on completion. CAVER is a
    separate process, so this does not block the caller's (GUI) thread."""
    cmd = build_command(java, caver_home, input_dir, config_path, out_dir, heap_mb)
    return subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            text=True, cwd=os.path.dirname(config_path) or None)


def find_clusters_timeless(folder):
    """Locate a clusters_timeless dir anywhere under `folder` (CAVER output), or None."""
    if not folder or not os.path.isdir(folder):
        return None
    for dirpath, _dirs, _files in os.walk(folder):
        if os.path.basename(dirpath) == 'clusters_timeless':
            return dirpath
    return None
