"""CAVER 3.0 integration for the Tunneler plugin -- locate (or fetch) the GPLv3 CAVER
engine, generate a run config, invoke it, and point at its output. Pure logic: NO tkinter,
NO yasara imports, so it is importable and unit-testable headlessly (unlike the GUI module).

IMPORTANT: this is a helper MODULE imported by the plugin, not a standalone plugin. It must
NOT begin with a plugin menu-header comment block -- YASARA scans every .py in plg/ and tries
to parse any such file as a plugin, then crashes on the non-conforming body (error 366, 'no
colon'). Like the other Tunneler_*.py helpers, it starts with a plain docstring so YASARA's
plugin scanner skips it. Keep the marker phrase out of this file entirely.

CAVER 3.0 (https://caver.cz) is separate GPLv3 software by Loschmidt Laboratories, Masaryk
University. This plugin does not redistribute it; it is fetched from the official site on
first use (source + license included in that download), or the user points at an existing
install. Only the GPLv3 CAVER 3.0 engine is used -- never the non-commercial CAVER Analyst /
CaverDock / Caver Web components.
"""

import math
import os
import shutil
import subprocess
import zipfile

# Official PLoS build: GPLv3, ships full source_code/ tree.
CAVER_DOWNLOAD_URL = 'https://www.caver.cz/fil/download/caver30/plos/caver_3.0.zip'
# Managed install location (user-writable, survives plugin updates). ~ expands via HOME.
DEFAULT_CAVER_ROOT = os.path.expanduser(os.path.join('~', '.tunneler', 'caver_3.0'))
# Remembers a resolved/browsed CAVER home across sessions. Kept OUT of Tunneler_config.ini
# (which Tunneler() rewrites every detection run and would wipe an unknown key).
CAVER_HOME_MEMO = os.path.expanduser(os.path.join('~', '.tunneler', 'caver_home.txt'))

# Minimal run config. The five run-time knobs are placeholders; everything else mirrors
# CAVER's own config_default.txt closely enough to produce the clusters_timeless output
# the importer reads. VMD/trajectory lines are dropped (we visualise in YASARA).
CONFIG_TEMPLATE = """\
# Generated by the YASARA Tunneler plugin -- CAVER 3.0 run config
load_tunnels no
load_cluster_tree no
stop_after never

time_sparsity 1
first_frame 1
last_frame 100000

# Tunnel origin (from the residue/atom picked in YASARA)
starting_point_coordinates {start_x:.3f} {start_y:.3f} {start_z:.3f}

probe_radius {probe_radius}
shell_radius {shell_radius}
shell_depth {shell_depth}

clustering average_link
weighting_coefficient 1
clustering_threshold {clustering_threshold}

exclude_start_zone 2
exclude_end_zone 0
min_middle_zone 5
save_zones no

one_tunnel_in_snapshot cheapest
max_output_clusters 999
save_dynamics_visualization no

generate_summary yes
generate_tunnel_characteristics yes
generate_tunnel_profiles yes
generate_histograms no
generate_bottleneck_heat_map no
generate_profile_heat_map no
compute_tunnel_residues no
compute_bottleneck_residues no

max_distance {max_distance}
desired_radius {desired_radius}
number_of_approximating_balls 12
add_central_sphere yes
max_number_of_tunnels 10000
max_limiting_radius 100
cost_function_exponent 2
automatic_shell_radius no
starting_point_protection_radius 4

frame_clustering yes
frame_weighting_coefficient 1
frame_clustering_threshold 1

average_surface_frame yes
average_surface_global yes

do_approximate_clustering no
generate_unclassified_cluster no

profile_tunnel_sampling_step 0.5
visualization_tunnel_sampling_step 1
visualize_tunnels_per_cluster 5000
visualization_subsampling random

compute_errors no
save_error_profiles no
generate_trajectory no

swap yes
seed 1
{include_line}"""


def find_java():
    """Path to the java launcher, or None if Java isn't on PATH."""
    return shutil.which('java')


def caver_home_valid(path):
    """True if `path` is a usable CAVER home (has caver.jar and a lib/ dir)."""
    return bool(path) and os.path.isfile(os.path.join(path, 'caver.jar')) \
        and os.path.isdir(os.path.join(path, 'lib'))


def _search_caver_home(root):
    """Find a dir containing caver.jar + lib/ anywhere under `root` (handles the zip's
    nested caver_3.0/caver/ layout), or None."""
    if not root or not os.path.isdir(root):
        return None
    for dirpath, dirs, files in os.walk(root):
        if 'caver.jar' in files and 'lib' in dirs:
            return dirpath
    return None


def remembered_caver_home():
    """The CAVER home saved by a previous browse/download, if still valid; else None."""
    try:
        with open(CAVER_HOME_MEMO) as f:
            path = f.read().strip()
    except OSError:
        return None
    return path if caver_home_valid(path) else None


def remember_caver_home(path):
    """Persist `path` as the CAVER home for future sessions (best-effort)."""
    try:
        os.makedirs(os.path.dirname(CAVER_HOME_MEMO), exist_ok=True)
        with open(CAVER_HOME_MEMO, 'w') as f:
            f.write(path)
    except OSError:
        pass


def find_caver_home(hint=None):
    """Return a valid CAVER home dir or None. Checks, in order: the explicit `hint` (which
    may be the caver dir itself, its parent run-root, or a tree to search), the remembered
    path from a previous session, then the managed install under DEFAULT_CAVER_ROOT.
    Returns None if nothing valid is found (caller then offers download / manual pick)."""
    for cand in (hint, os.path.join(hint or '', 'caver')):
        if caver_home_valid(cand):
            return cand
    remembered = remembered_caver_home()
    if remembered:
        return remembered
    for root in (hint, DEFAULT_CAVER_ROOT):
        found = _search_caver_home(root)
        if found:
            return found
    return None


def download_caver(progress_cb=None, url=CAVER_DOWNLOAD_URL, dest_root=DEFAULT_CAVER_ROOT):
    """Download + extract the official CAVER zip into `dest_root`; return the caver home
    dir. `progress_cb(pct)` is called during download if given. Raises on failure."""
    import urllib.request
    os.makedirs(dest_root, exist_ok=True)
    zip_path = os.path.join(dest_root, '_caver_download.zip')

    def _hook(blocks, blocksize, total):
        if progress_cb and total > 0:
            progress_cb(min(100, int(blocks * blocksize * 100 / total)))

    try:
        urllib.request.urlretrieve(url, zip_path, _hook)
        with zipfile.ZipFile(zip_path) as z:
            z.extractall(dest_root)
    finally:
        if os.path.exists(zip_path):
            os.remove(zip_path)
    home = _search_caver_home(dest_root)
    if not home:
        raise RuntimeError('CAVER downloaded but caver.jar was not found after extraction.')
    return home


def make_config(start_xyz, probe_radius=0.9, shell_radius=3, shell_depth=4,
                clustering_threshold=3.5, max_distance=3, desired_radius=5,
                include_residue_names=None):
    """Return the text of a CAVER config for a single static structure, with the tunnel
    origin fixed at `start_xyz` (a 3-tuple in the structure's coordinate frame).

    `max_distance`/`desired_radius` drive CAVER's starting-point optimization: from the
    given origin CAVER walks up to `max_distance` A toward open space, stopping once it
    finds a spot with `desired_radius` A of clearance (or the roomiest point within reach).
    A larger `max_distance` makes picking forgiving -- the user can mark an atom near a
    cavity rather than exactly inside it -- at the cost of possibly drifting into an
    adjacent pocket, so keep it modest."""
    x, y, z = start_xyz
    include_line = ('include_residue_names ' + include_residue_names) if include_residue_names else ''
    return CONFIG_TEMPLATE.format(
        start_x=x, start_y=y, start_z=z,
        probe_radius=probe_radius, shell_radius=shell_radius,
        shell_depth=shell_depth, clustering_threshold=clustering_threshold,
        max_distance=max_distance, desired_radius=desired_radius,
        include_line=include_line)


# ---------------------------------------------------------------------------
# Start-point snapping
# ---------------------------------------------------------------------------
# CAVER's own start optimization (max_distance/desired_radius) is a local greedy
# climb toward the biggest empty sphere -- it is blind to whether that sphere is a
# buried cavity or a surface dimple, so raising its leash to reach a mis-picked
# start just as easily drifts onto the surface or into a neighbouring pocket. We
# have the whole structure in hand, so we can do better before CAVER ever runs:
# climb toward maximum clearance *subject to staying buried*, which is exactly the
# constraint CAVER omits. `atoms` is a list of (x, y, z, vdw_radius) tuples in the
# same coordinate frame as `pick` -- pass the water-excluded protein atoms, i.e.
# the same set CAVER will see. All pure math (no numpy) so it stays headless.

def _sphere_directions(n):
    """`n` roughly-uniform unit vectors on the sphere (deterministic Fibonacci spiral)."""
    dirs = []
    golden = math.pi * (3.0 - math.sqrt(5.0))
    for i in range(n):
        z = 1.0 - (2.0 * i + 1.0) / n
        r = math.sqrt(max(0.0, 1.0 - z * z))
        theta = golden * i
        dirs.append((r * math.cos(theta), r * math.sin(theta), z))
    return dirs


def point_clearance(point, atoms):
    """Radius of the largest empty sphere centred at `point`: min over atoms of
    (centre distance - vdW radius). Negative if `point` sits inside an atom."""
    px, py, pz = point
    best = float('inf')
    for ax, ay, az, ar in atoms:
        d = math.sqrt((px - ax) ** 2 + (py - ay) ** 2 + (pz - az) ** 2) - ar
        if d < best:
            best = d
    return best


def point_burial(point, atoms, directions, ray_length=10.0, probe=0.0):
    """Fraction of `directions` in which a ray from `point` hits an atom within
    `ray_length` A. ~1.0 = enclosed (buried), low = open to solvent (surface)."""
    px, py, pz = point
    blocked = 0
    for ux, uy, uz in directions:
        for ax, ay, az, ar in atoms:
            wx, wy, wz = ax - px, ay - py, az - pz
            t = wx * ux + wy * uy + wz * uz          # projection onto the ray
            if t <= 0.0 or t > ray_length:
                continue
            rr = ar + probe
            if (wx * wx + wy * wy + wz * wz) - t * t <= rr * rr:  # perp dist^2 <= r^2
                blocked += 1
                break
    return blocked / len(directions) if directions else 0.0


def snap_start_point(pick, atoms, max_step=4.0, burial_min=0.6,
                     directions=32, ray_length=10.0, step0=1.0, step_min=0.1):
    """Move `pick` toward the roomiest nearby *buried* spot and report the result.

    Pattern-search hill-climb: from the current best, probe the `directions` unit
    vectors at the current step size, keep the move with the largest clearance that
    both stays within `max_step` A of the original pick and keeps burial >=
    `burial_min`; halve the step when no probe improves; stop at `step_min`.

    Returns a dict: snapped (x,y,z), clearance, burial, displacement (A moved), and
    pick_clearance / pick_burial for the raw pick (drives the 'looks surface/tight'
    warning). Purely advisory -- the caller decides whether to use `snapped`."""
    dirs = _sphere_directions(directions)
    # Prefilter to atoms a ray could reach from anywhere in the search ball -- one
    # pass, then clearance/burial only scan this local subset.
    reach = max_step + ray_length + 3.0
    px, py, pz = pick
    near = [a for a in atoms
            if (a[0] - px) ** 2 + (a[1] - py) ** 2 + (a[2] - pz) ** 2 <= reach * reach]
    if not near:
        near = atoms

    def clr(p):
        return point_clearance(p, near)

    def bur(p):
        return point_burial(p, near, dirs, ray_length)

    origin = pick
    pick_clear = clr(pick)
    pick_bur = bur(pick)
    best, best_clear = pick, pick_clear
    step = step0
    while step >= step_min:
        improved = False
        for ux, uy, uz in dirs:
            cand = (best[0] + ux * step, best[1] + uy * step, best[2] + uz * step)
            dx, dy, dz = cand[0] - origin[0], cand[1] - origin[1], cand[2] - origin[2]
            if dx * dx + dy * dy + dz * dz > max_step * max_step:
                continue
            if bur(cand) < burial_min:
                continue
            c = clr(cand)
            if c > best_clear + 1e-6:
                best, best_clear, improved = cand, c, True
        if not improved:
            step *= 0.5
    disp = math.sqrt(sum((best[i] - origin[i]) ** 2 for i in range(3)))
    return {'snapped': best, 'clearance': best_clear, 'burial': bur(best),
            'displacement': disp, 'pick_clearance': pick_clear, 'pick_burial': pick_bur}


def build_command(java, caver_home, input_dir, config_path, out_dir, heap_mb=2000):
    """Assemble the CAVER launch command (matches the package's own static examples:
    java -jar caver.jar -home <caver> -pdb <input dir> -conf <config> -out <out>)."""
    return [java, '-Xmx{}m'.format(heap_mb), '-jar',
            os.path.join(caver_home, 'caver.jar'),
            '-home', caver_home, '-pdb', input_dir, '-conf', config_path, '-out', out_dir]


def start_caver(java, caver_home, input_dir, config_path, out_dir, heap_mb=2000):
    """Launch CAVER as a background subprocess and return the Popen handle. stdout/stderr
    are captured so the caller can poll .poll() and read output on completion. CAVER is a
    separate process, so this does not block the caller's (GUI) thread."""
    cmd = build_command(java, caver_home, input_dir, config_path, out_dir, heap_mb)
    return subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            text=True, cwd=os.path.dirname(config_path) or None)


def find_clusters_timeless(folder):
    """Locate a clusters_timeless dir anywhere under `folder` (CAVER output), or None."""
    if not folder or not os.path.isdir(folder):
        return None
    for dirpath, _dirs, _files in os.walk(folder):
        if os.path.basename(dirpath) == 'clusters_timeless':
            return dirpath
    return None
